Repository lodgify/lodgify-ui, pull requests merged in 2018-05, with the labels that each got.

#130 TE-353 Update colours
  .gitignore
  styleguide/assets/07-Brother1816-Regular.otf
  styleguide/assets/15-Brother1816-Black.otf
  styleguide/assets/lego-repeat.png
  styleguide/config/options/styles.js
  styleguide/config/options/template.js
  styleguide/config/options/theme.js
  styleguide/styleguide-components/StyleGuideRenderer/component.js
Labels: :wave: David - have a look

#131 TE-350 Side-by-side editor
  lib/with-responsive/withResponsive.js
  lib/with-responsive/withResponsive.spec.js
  src/components/collections/Form/Readme.md
  src/components/general-widgets/CallMeBack/Readme.md
  src/components/general-widgets/Contact/Readme.md
  src/components/general-widgets/OwnerLogin/Readme.md
  src/components/general-widgets/OwnerSignUp/Readme.md
  styleguide/config/base.js
  styleguide/config/options/theme.js
  styleguide/styleguide-components/AlphaFlag/component.js
  styleguide/styleguide-components/PlaygroundRenderer/component.js
  styleguide/styleguide-components/PlaygroundRenderer/index.js
  styleguide/styleguide-components/StyleGuideRenderer/component.js
  styleguide/styleguide-components/index.js
Labels: :wave: David - have a look

#132 TE-356 little fixes
  styleguide/config/options/styles.js
  styleguide/config/options/theme.js
  styleguide/styleguide-components/LogoRenderer/component.js
  styleguide/styleguide-components/LogoRenderer/logo.png
  styleguide/styleguide-components/MobilePlaceholder/component.js
Labels: :wave: David - have a look

#133 TE-355 Add 'Get started' copy
  styleguide/config/options/styles.js
  styleguide/docs/getStarted.md
  styleguide/styleguide-components/PlaygroundRenderer/component.js
Labels: :wave: David - have a look

#134 TE-357 Alpha ribbin z-index fix
  styleguide/styleguide-components/AlphaFlag/component.js
  styleguide/styleguide-components/MobilePlaceholder/component.js
Labels: :wave: David - have a look

#135 TE-358 Clean up npm tasks
  Jenkinsfile
  Readme.md
  package.json
Labels: :wave: David - have a look

#136 TE-359 Fixes from sprint review
  package.json
  styleguide/config/options/theme.js
  styleguide/styleguide-components/PlaygroundRenderer/component.js
  styleguide/styleguide-components/StyleGuideRenderer/component.js
Labels: :wave: David - have a look

#143 TE-369 Add z-index map on style guide components
  styleguide/config/options/theme.js
  styleguide/styleguide-components/AlphaFlag/component.js
  styleguide/styleguide-components/MobilePlaceholder/component.js
  styleguide/styleguide-components/StyleGuideRenderer/component.js
Labels: :wave: David - have a look

#142 TE-370 Expose built styles to API
  package.json
  src/styles/lodgify-ui.less
  styleguide/config/base.js
  styleguide/docs/getStarted.md
  styleguide/webpack.config.js
  tools/jest/jest.config.js
  tools/webpack/less.build.config.js
Labels: :wave: David - have a look

#146 TE-362 Update heading size of the getting started documentation
  .gitignore
  styleguide/docs/getStarted.md
Labels: :wave: David - have a look

#150 TE-377 Switch Jenkins for Travis
  .travis.yml
  Jenkinsfile
  Readme.md
  package.json
Labels: :wave: David - have a look

#148 TE-362 Fix component imports
  styleguide/config/base.js
  styleguide/config/options/componentPathLine.js
  styleguide/docs/getStarted.md
Labels: :wave: David - have a look

#151 TE-379 Add branch:production condition to gh-pages deploy step
  .travis.yml
Labels: :wave: David - have a look

#149 TE-372 Update readme
  Readme.md
  docs/CONTRIBUTING.md
  docs/CONVENTIONS.md
Labels: :wave: David - have a look

#153 TE-376 Test install semantic-release
  .travis.yml
  package.json
Labels: :wave: David - have a look

#154 TE-376 Set semantic-release branch to production
  .travis.yml
Labels: :wave: David - have a look, :wave: Jonny - have a look

#155 TE-383 Fix CONTRIBUTING.md broken link
  docs/CONTRIBUTING.md
Labels: :wave: Marc - have a look

#156 TE-389 Remove the babel dependency
  package.json
Labels: :wave: David - have a look

#157 TE-384 Add slack notification integration
  .travis.yml
Labels: :wave: David - have a look

#164 TE-398 Add Table collection
  src/components/collections/Table/Readme.md
  src/components/collections/Table/component.js
  src/components/collections/Table/component.spec.js
  src/components/collections/Table/index.js
  src/components/collections/Table/mock-data/props.js
  src/styles/semantic/semantic.less
  src/styles/semantic/theme.config
  src/styles/semantic/themes/livingstone/collections/table.variables
Labels: :wave: David - have a look

#168 TE-387 Implement @lodgify/enzyme-jest-expect-helpers
  docs/CONVENTIONS.md
  package.json
  src/components/collections/Table/component.spec.js
  src/components/elements/Button/component.spec.js
  src/components/elements/GoogleMap/component.spec.js
  src/components/elements/Icon/component.spec.js
  src/components/elements/IconCard/component.spec.js
  src/components/elements/Quote/component.spec.js
  src/components/general-widgets/Container/component.spec.js
  src/components/general-widgets/FeaturedProperty/component.spec.js
  src/components/general-widgets/Review/component.spec.js
  src/components/general-widgets/SearchBar/component.spec.js
  src/components/inputs/DateRangePicker/component.spec.js
  src/components/layout/Grid/component.spec.js
  src/components/layout/GridColumn/component.spec.js
  src/components/layout/GridRow/component.spec.js
  src/components/layout/ShowOnDesktop/component.spec.js
  src/components/layout/ShowOnMobile/component.spec.js
  src/components/media/Thumbnail/component.spec.js
  src/components/property-page-widgets/Amenities/component.spec.js
  src/components/property-page-widgets/Description/component.spec.js
  src/components/property-page-widgets/HostProfile/component.spec.js
  src/components/property-page-widgets/KeyFacts/component.spec.js
  src/components/property-page-widgets/Location/component.spec.js
  src/components/property-page-widgets/Location/utils/getTransportOptionsMarkup.spec.js
  src/components/property-page-widgets/PaymentInformation/component.spec.js
  src/components/property-page-widgets/Pictures/component.spec.js
  src/components/property-page-widgets/Reviews/component.spec.js
  src/components/property-page-widgets/Rules/component.spec.js
  src/components/property-page-widgets/SleepingArrangements/component.spec.js
  src/components/typography/Subheading/component.spec.js
  src/utils/expect-helpers/expectComponentToBe.js
  src/utils/expect-helpers/expectComponentToHaveChildren.js
  src/utils/expect-helpers/expectComponentToHaveDisplayName.js
  src/utils/expect-helpers/expectComponentToHaveProps.js
  src/utils/expect-helpers/index.js
  src/utils/with-responsive/withResponsive.spec.js
Labels: :wave: David - have a look
